services:
  rct:
    build: .
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./config/youtube:/app/config/youtube
    # Host IP for connecting to OBS on macOS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OBS_WS_HOST=host.docker.internal
